//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repozitorijumi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartaUSpilu
    {
        public int KartaUSpiluID { get; set; }
        public int SpilID { get; set; }
        public string NazivKarte { get; set; }
        public string Sekcija { get; set; }
        public byte Kolicina { get; set; }
    
        public virtual Spil Spil { get; set; }
    }
}
