//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repozitorijumi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spil()
        {
            this.KartaUSpilus = new HashSet<KartaUSpilu>();
        }
    
        public int SpilID { get; set; }
        public string Naziv { get; set; }
        public string Format { get; set; }
        public string Arhetip { get; set; }
        public string Status { get; set; }
        public int TakmicarID { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public string NapomenaSudije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartaUSpilu> KartaUSpilus { get; set; }
    }
}
